version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ideas
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/ideas
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      
# Using bind mounts instead of named volumes
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/postgres
      o: bind